[build]
    functions = "lambda"
    command = "npm run build"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Headers = "Origin"
      Access-Control-Allow-Headers = "X-Requested-With"
      Access-Control-Allow-Headers = "Content-Type"
      Access-Control-Allow-Headers = "Accept"
      Access-Control-Allow-Headers = "Authorization"